// Measurements of all features of the arena

#ifndef __GEOMETRY__
#define __GEOMETRY__


#define CENTERX (0)
#define CENTERY (0)

#define SCALE_FACTOR    ((float)3.367) 

// The Arena Dimensions
#define FIELD_LENGHT    (2000/SCALE_FACTOR)
#define FIELD_WIDTH     (1500/SCALE_FACTOR)


// The Goals
#define GOAL_RIGHT_NORTH_X (1000/SCALE_FACTOR)
#define GOAL_RIGHT_NORTH_Y (200/SCALE_FACTOR)

#define GOAL_RIGHT_CENTER_X (1000/SCALE_FACTOR)
#define GOAL_RIGHT_CENTER_Y (0/SCALE_FACTOR)

#define GOAL_RIGHT_SOUTH_X (1000/SCALE_FACTOR)
#define GOAL_RIGHT_SOUTH_Y (-200/SCALE_FACTOR)

#define GOAL_LEFT_NORTH_X (-1000/SCALE_FACTOR)
#define GOAL_LEFT_NORTH_Y (200/SCALE_FACTOR)

#define GOAL_LEFT_CENTER_X (-1000/SCALE_FACTOR)
#define GOAL_LEFT_CENTER_Y (0)

#define GOAL_LEFT_SOUTH_X (-1000/SCALE_FACTOR)
#define GOAL_LEFT_SOUTH_Y (-200/SCALE_FACTOR)


// The Dees
#define DEE_RIGHT_NORTH_X (600/SCALE_FACTOR)
#define DEE_RIGHT_NORTH_Y (450/SCALE_FACTOR)

#define DEE_RIGHT_SOUTH_X (600/SCALE_FACTOR)
#define DEE_RIGHT_SOUTH_Y (-450/SCALE_FACTOR)

#define DEE_LEFT_NORTH_X (-600/SCALE_FACTOR)
#define DEE_LEFT_NORTH_Y (450/SCALE_FACTOR)

#define DEE_LEFT_SOUTH_X (-600/SCALE_FACTOR)
#define DEE_LEFT_SOUTH_Y (-450/SCALE_FACTOR) 

# endif
